### PR TITLE
Fix a crash in connman bearer backend on d'tor when using QStringLiteral

### PR DESCRIPTION
**Pull request by chriadam**
Task-number: QTBUG-41507
Change-Id: I7711eb34bf9ca738fb25031acff3371a6126ae23
Reviewed-by: Christopher Adams chris.adams@jollamobile.com

### CODE REVIEW

**Comment by chriadam** [comment]
@sletta @rburchell @lpotter @monich @VDVsx

**Comment by VDVsx** [comment]
LGTM

**Comment by monich** [comment]
LGTM, doesn't crash anymore.

**Comment by monich** [comment]
Can somebody please merge it?

**Pull request merged**
