### PR TITLE
[qtbase] Allow QGenericUnixTheme parameters to be configured. Contributes to MER#1361

### PR DESCRIPTION
**Pull request by matthewvogt**
Configuration via QtProject/QPlatformTheme.conf

### CODE REVIEW

**Comment by amccarthy** [comment]
LGTM

**Comment by jpetrell** [comment]
LGTM. Works nicely on the device too. Shouldn't we introduce this to upstream Qt?

**Comment by matthewvogt** [comment]
It has been pointed out that using QSettings here allows potentially malicious use - introducing values into ~/.config/.../x.conf that override the system values and cause trouble.  Personally, I think this is a reasonable risk which is easy to rectify, but I don't want to have to argue that in the Qt Project...

**Comment by matthewvogt** [comment]
Added this change for qtdeclarative parameters: https://github.com/mer-qt/qtdeclarative/pull/82

**Comment by matthewvogt** [comment]
Updated to restrict the settings lookup to the system directories, which prevents loading malicious configuration settings from the user directory.

**Pull request merged**
